# Generated by Django 3.2.7 on 2021-12-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocard_model',
            name='salesid',
        ),
        migrations.RemoveField(
            model_name='addtocard_model',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Feeback_Model',
        ),
        migrations.DeleteModel(
            name='Addtocard_Model',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
